on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: node install, build, and test
        run: |
          npm --prefix ${GITHUB_WORKSPACE}/src/front install
          npm --prefix ${GITHUB_WORKSPACE}/src/front run build --if-present
          npm --prefix ${GITHUB_WORKSPACE}/src/front test
